 CREATE DATABASE IF NOT EXISTS RobbeGeusens;
 use RobbeGeusens;

CREATE TABLE IF NOT EXISTS Products (
    ProductID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    ProductName VARCHAR(64),
    Descript TEXT,
    Stock INT UNSIGNED NOT NULL,
    WeightG INT UNSIGNED NOT NULL,
    Resizable TINYINT(1) UNSIGNED,
    Electrical TINYINT(1) UNSIGNED,
    Diameter INT UNSIGNED,
    Manufacturer VARCHAR(100),
    HeadType VARCHAR(1),
    ProductType VARCHAR(1) NOT NULL,
    PRIMARY KEY (ProductID)
);

CREATE TABLE IF NOT EXISTS Kits (
    KitID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    KitName VARCHAR(64),
    KitPrice INT UNSIGNED NOT NULL,
    Descript TEXT,
    WeightG INT UNSIGNED NOT NULL,
    IsKit TINYINT(1) UNSIGNED NOT NULL,
    PRIMARY KEY (KitID)
);

CREATE TABLE IF NOT EXISTS KitProducts (
    KitID INT UNSIGNED NOT NULL,
    ProductID INT UNSIGNED NOT NULL,
    Quantity INT UNSIGNED NOT NULL,
    FOREIGN KEY (KitID) REFERENCES Kits(KitID),
    FOREIGN KEY (ProductID) REFERENCES Products(ProductID),
    PRIMARY KEY (KitID, ProductID)
);

CREATE TABLE IF NOT EXISTS Images (
    ImageID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    KitID INT UNSIGNED NOT NULL,
    Link VARCHAR(100),
    PRIMARY KEY (ImageID),
    FOREIGN KEY (KitID) REFERENCES Kits(KitID)
);

CREATE TABLE IF NOT EXISTS Addresses (
    AddressID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    Country VARCHAR(56),
    PostalCode INT(7) UNSIGNED,
    City VARCHAR(85),
    Street VARCHAR(100),
    Nr INT UNSIGNED,
    PRIMARY KEY (AddressID)
);

CREATE TABLE IF NOT EXISTS Users (
    UserID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    FirstName VARCHAR(32),
    LastName VARCHAR(32),
    Email VARCHAR(100),
    Passwd VARCHAR(64),
    AddressID INT UNSIGNED,
    BirthDate DATE,
    Administrator TINYINT(1) UNSIGNED,
    PRIMARY KEY (UserID),
    FOREIGN KEY (AddressID) REFERENCES Addresses(AddressID)
);

CREATE TABLE IF NOT EXISTS Shops (
    ShopID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    ShopName VARCHAR(32),
    AddressID INT UNSIGNED NOT NULL,
    PRIMARY KEY (ShopID),
    FOREIGN KEY (AddressID) REFERENCES Addresses(AddressID)
);

CREATE TABLE IF NOT EXISTS ShopSupply (
    ShopID INT UNSIGNED NOT NULL,
    KitID INT UNSIGNED NOT NULL,
    Supply INT UNSIGNED NOT NULL,
    FOREIGN KEY (ShopID) REFERENCES Shops(ShopID),
    FOREIGN KEY (KitID) REFERENCES Kits(KitID),
    PRIMARY KEY (ShopID, KitID)
);

CREATE TABLE IF NOT EXISTS Orders (
    OrderID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    UserID INT UNSIGNED NOT NULL,
    Discount INT UNSIGNED,
    PlacementDate DATE,
    DeliveryDate DATE,
    PlacedShop INT UNSIGNED NOT NULL,
    DeliveryAddress INT UNSIGNED NOT NULL,
    HouseDelivery TINYINT(1) UNSIGNED,
    DeliveryCost INT UNSIGNED,
    Payed TINYINT(1) UNSIGNED,
    PRIMARY KEY (OrderID),
    FOREIGN KEY (UserID) REFERENCES Users(UserID),
    FOREIGN KEY (PlacedShop) REFERENCES Shops(ShopID),
    FOREIGN KEY (DeliveryAddress) REFERENCES Addresses(AddressID)
);

CREATE TABLE IF NOT EXISTS OrderedKits (
    OrderID INT UNSIGNED NOT NULL,
    KitID INT UNSIGNED NOT NULL,
    Quantity INT UNSIGNED NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES Orders(OrderID),
    FOREIGN KEY (KitID) REFERENCES Kits(KitID),
    PRIMARY KEY (OrderID, KitID)
);